---
- name: nick playbook
  hosts: all
  become: True
  tasks:
    - name: Install apache server
      apt:
        name: "apache2"
        state: "present"

    - name: Enable apache on reboot
      service:
        name: apache2
        state: started
        enabled: True

...
 
